language: node_js
node_js:
  - lts/*

before_install: cp ci/.npmrc .npmrc

script: yarn build

before_deploy:
  - echo "$ENCRYPTION_PASSPHRASE" | gpg --passphrase-fd 0 --decrypt deploy/key.gpg

deploy:
  provider: pages:git
  edge: true
  local_dir: public
  deploy_key: deploy/key
  on:
    branch: master
    repo: jiripudil/jiripudil.cz

cache: yarn

notifications:
  email: false
