language: php

php:
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - php ./vendor/bin/parallel-lint -e php,phpt --exclude ./vendor .

script: ./vendor/bin/tester -c ./tests/php-unix.ini ./tests/jiripudilTests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
